<section class="user-dashboard page-spacing">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="dashboard-heading">
                    <h1><img src="<?php echo $themeUrl ?>/frontend/images/bonus-pool.png" class="img-fluid">Premier Shopper Bonus Pool</h1>
                </div>
            </div>
            <?php $this->load->view('frontend/user/dashboard_nav_bar'); ?>
        </div>
    </div>
    <?php $this->load->view('frontend/user/dashboard_info_bar'); ?>
</section>
<!--====  End of Dashbaord====-->
<!--=========================================
=            Dashbaord          =
==========================================-->
<section class="bonus-poll-sec page-spacing">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h3>
                    <?php if(is_array($req)){ echo $req['req_1']; } ?>
                    Payments are processed on the 1st business day of each month!
                </h3>
                <div class="example-working">
                    <h2>Example of How it Works…</h2>
                    <div class="attention-box">
                        <p><strong>Attention:</strong> This example is for illustration purposes only! It is not meant as a promise of income, nor is it intended to represent the current sales volume of Karmora.</p>
                    </div>
                    <ul class="list-inline bouns-poll-list">
                        <li><span>You have 10 Premier Shoppers and 20 Casual Shoppers in your Shopping Community in June.   You have met the minimum requirement for 5 Premier Shoppers and are elgible for Profit Sharing distribution.</span></li>
                        <li><span>The Shopping Revenue generated by all Karmora Shoppers in the month of June is $500,000.</span></li>
                        <li><span>$500,000 x 10% = $50,000 that is deposited in the Profit Sharing Pool.</span></li>
                        <li><span>Your Shopping Community generated $500 in Shopping Revenue in June.</span></li>
                        <li><span>80 Premier Shoppers qulaified for the Profit Sharing Program in June.</span></li>
                        <li><span>The Shopping Revenue generated from the Shopping Communities of all the Qualifying Premier Shoppers is $30,000.</span></li>
                        <li><span>You share in the Profit Sharing Pool would be 1.6%. It represents the Shopping Revenue generated by your Shopping Community divided by the Shopping Revenue of all Qualifying Shoppers ($500 ÷ $30,000 = 1.66%).</span></li>
                        <li><span>Your Profit Sharing Payment would be $830. It is calculated by multiplying the $50,000 in the Profit Sharing Pool and your 1.66% Pool Percentage ($50,000 x 1.66% = $830).</span></li>
                        <li><span>Not too shabby for simply sharing Karmora ads on Facebook, Twitter and Pinterest!</span></li>
                        <li><span>Now… keep sharing ads to attract more Shoppers to your Community and claim more of the Profit Sharing Pool next month!</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!--====  End of Dashbaord====-->
