<section class="profit-sharing-sec compensation-page-sec page-spacing">
   <div class="container">
      <div class="profit-sharing-cover">
         <div class="row">
            <div class="col-12">
               <div class="top-heading-cover">
                  <h1>It Pays to Share Good Karmora!</h1>
               </div>
            </div>
         </div>
         <div class="row">
            <div class="col-7">
               <div class="profit-sharing-content">
                  <h3>The Opportunity</h3>
                  <p>Did you know that this year more than <strong>200 Million</strong> US Consumers will spend more than <strong>$250 Billion</strong> shopping online, and that the volume is expected to grow every year!   Karmora provides everything you need to build a massive online hopping Community paying you generous <strong>Recurring Commissions</strong> on every purchase made by every Shopper.   It's as easy as sharing our premade advertisements with all of your social media friends and watching in amazement as your Shopping Community and income explodes!  </p>
                  <p>And the fun doesn’t stop with getting paid on every purchase made by your Shopping Community…   Each month that you have a minimum of 5 Premier Shoppers in your Shopping Community you can qulaify for our Premier Shopper Bonus Pool where you will <strong>earn a percentage of every purchase… made by every Shopper in the ENTIRE COMPANY!</strong>   It’s Good Karmora in action!</p>
               </div>
            </div>
            <div class="col-5">
               <div class="profit-img-cover">
                  <img src="<?php echo $themeUrl ?>/frontend/images/us-state.png" alt="">
               </div>
            </div>
         </div>
      </div>
      <div class="profit-sharing-cover">
         <div class="row">
            <div class="col-12">
               <div class="top-heading-cover">
                  <h1>Build a Shopping Community and Get Paid!</h1>
               </div>
            </div>
         </div>
         <div class="row">
            <div class="col-5">
               <div class="recurring-cover">
                  <img src="<?php echo $themeUrl ?>/frontend/images/Recurring-Commissions.jpg" alt="">
               </div>
            </div>
            <div class="col-7">
               <div class="profit-sharing-content">
                  <h3>The Most Generous Online Shopping Commissions Ever!</h3>
                  <ul class="list-inline">
                     <li class="list-inline-item"><span>Earn 20% Recurring Commissions on every Exclusive Product purchased by every Shopper in your Shopping Community.   It’s as easy as sharing Karmora ads on your favorite social media channels and watching in amazement as your Shopping Community and income grows!</span></li>
                     <li class="list-inline-item"><span>Earn 5% Recurring Cash Back Override Commissions on every Cash Back dollar paid to every Shopper in your Shopping Community!</span></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
      <div class="profit-sharing-cover">
         <div class="row">
            <div class="col-12">
               <div class="top-heading-cover">
                  <h1>Premier Shopper Bonus Pool</h1>
               </div>
            </div>
         </div>
         <div class="row">
            <div class="col-5">
               <div class="recurring-cover profit-cover">
                  <img src="<?php echo $themeUrl ?>/frontend/images/profie-sharing.jpg" alt="">
               </div>
            </div>
            <div class="col-7">
               <div class="profit-sharing-content">
                  <p>The Premier Shopper Bonus Pool is the most generous incentive program in online shopping!   Enroll and maintain 5 Premier Shoppers in your Shopping Community and you qualify to <strong>earn a percentage of every purchase… made by every Shopper… in the entire Company!</strong></p>
                  <p>Participating in the Premier Shopper Bonus Pool is as easy as 1… 2… 3!</p>
                  <ul class="list-inline list-profit">
                     <li class="list-inline-item"><span><strong>Step 1:</strong>Only Premier Shoppers can participate.</span></li>
                     <li class="list-inline-item"><span><strong>Step 2:</strong>Enroll a minimum of 5 Premier Shoppers to qualify to be paid in the Bonus Pool containing 10% of the total revenue generated by all Shoppers!</span></li>
                     <li class="list-inline-item"><span><strong>Step 3:</strong>Share Good Karmora with everyone you know!   The more <a href="">active shoppers</a> in your Shopping Community each month… the more you will earn in the Bonus Pool!</span></li>
                  </ul>
                  <a href="<?php echo base_url('profit-sharing-program');?>" class="btn btn-joinnow left-right-hover">Tell Me More!</a>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
