<section class="profit-sharing-sec page-spacing">
    <div class="container">
        <div class="profit-sharing-cover">
            <div class="row">
                <div class="col-6">
                    <div class="profit-img-cover">
                        <img src="<?php echo $themeUrl ?>/frontend/images/profie-sharing.jpg" alt="">
                    </div>
                </div>
                <div class="col-6">
                    <div class="profit-sharing-content">
                        <h3>Premier Shopper Bonus Pool</h3>
                        <p>Shopping Community builders are the backbone of our company and the Premier Shopper Bonus Pool is designed to reward our most successful community builders for their efforts!   Each month Karmora deposits 10% of our total company revenue into a Bonus Pool reserved for our Premier Shoppers.</p>
                        <p>Your share in the pool is determined by the Shopping Revenue generated by your Shopping Community versus that of other eligible Premier Shopper Communities. The more Shoppers in your Shopping Community making Cash Back and Exclusive Product purchases each month… the bigger your Bonus will be!   Here’s how it works…</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="qulify-cover">
            <div class="row">
                <div class="col-12">
                    <h3>How to Qualify:</h3>
                    <ul class="list-inline">
                        <li class="list-inline-item"><span>You must be a Premier Shopper to participate.</span></li>
                        <li class="list-inline-item"><span>You must have a minimum of 5 Premier Shoppers in your Shopping Community each month to qualify to be paid.</span></li>
                        <li class="list-inline-item"><span>You must have made an Exclusive Product Purchase of any amount during the Qualifying Period.</span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="qulify-cover">
            <div class="row">
                <div class="col-12">
                    <h3>Profit Sharing Payout Details:</h3>
                    <ul class="list-inline">
                        <li class="list-inline-item"><span>Bonus Payments are deposited in your eWallet on or before the 5th business day of each calendar month for the previous months’ revenue.</span></li>
                        <li class="list-inline-item"><span>Your share of the Bonus Pool is based on the Shopping Revenue generated by your Shopping Community versus the Shopping Revenue generated by the Communities of other Bonus Pool eligible Premier Shoppers.</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!--====  End of Blog Homepage ====-->


<section class="bonus-poll-sec profit-sharing-pool page-spacing">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="example-working">
                    <h2>Example of How it Works…</h2>
                    <div class="attention-box">
                        <p><strong>Attention:</strong> This example is for illustration purposes only! It is not meant as a promise of income, nor is it intended to represent the current sales volume of Karmora.</p>
                    </div>
                    <ul class="list-inline bouns-poll-list">
                        <li><span>You have 10 Premier Shoppers and 20 Casual Shoppers in your Shopping Community in June.   You have met the minimum requirement for 5 Premier Shoppers and are elgible for Profit Sharing distribution.</span></li>
                        <li><span>The Shopping Revenue generated by all Karmora Shoppers in the month of June is $500,000.</span></li>
                        <li><span>$500,000 x 10% = $50,000 that is deposited in the Profit Sharing Pool.</span></li>
                        <li><span>Your Shopping Community generated $500 in Shopping Revenue in June.</span></li>
                        <li><span>80 Premier Shoppers qulaified for the Profit Sharing Program in June.</span></li>
                        <li><span>The Shopping Revenue generated from the Shopping Communities of all the Qualifying Premier Shoppers is $30,000.</span></li>
                        <li><span>You share in the Profit Sharing Pool would be 1.6%. It represents the Shopping Revenue generated by your Shopping Community divided by the Shopping Revenue of all Qualifying Shoppers ($500 ÷ $30,000 = 1.66%).</span></li>
                        <li><span>Your Profit Sharing Payment would be $830. It is calculated by multiplying the $50,000 in the Profit Sharing Pool and your 1.66% Pool Percentage ($50,000 x 1.66% = $830).</span></li>
                        <li><span>Not too shabby for simply sharing Karmora ads on Facebook, Twitter and Pinterest!</span></li>
                        <li><span>Now… keep sharing ads to attract more Shoppers to your Community and claim more of the Profit Sharing Pool next month!</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

